[mgr]
prepend_keymap = [
    { on = "?", run = "help", desc = "Open help" },
    { on = "Z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
    { on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
]
